### ISSUE TITLE
Add features to match those of the cli

### ISSUE THREAD

**Issue by seadanda** [seadanda/protonvpn-applet#2]
Features to add:

- [ ]     protonvpn init
- [x]     connect
    - [x]     fastest
    - [x]     country [dropdown list] ?
    - [x]     secure core
    - [x]     p2p
    - [x]     tor
    - [x]     random
- [x]     reconnect to last server
- [x]     disconnect
- [x]     status
- [ ]     configure
- [x]     refresh
- [x]     protonvpn version
- [x]     applet version

**Comment by peytondmurray** [comment]
Working on a few of these right now, will make a PR when ready.
