### ISSUE TITLE
Cannot parse protonvpn-cli status output.

### ISSUE THREAD

**Issue by elshize** [seadanda/protonvpn-applet#8]
Hi,

I'm running the applet with protonvpn-cli v2.2.4 and it runs for a while, but then always eventually exits with the following message (including the entire program log):

```
qt5ct: using qt5ct plugin
qt5ct: D-Bus system tray: no
qt5ct: palette support is disabled
qt5ct: updating settings..
qt5ct: updating settings..
Traceback (most recent call last):
  File "/usr/bin/protonvpn-applet", line 68, in run
    raise VPNStatusException('Cannot parse protonvpn-cli status output.')
__main__.VPNStatusException: Cannot parse protonvpn-cli status output.
```

I'm on manjaro and am using the AUR package.

Let me know if I can help with any additional information.

**Comment by elshize** [comment]
An update: I've tried running it several times, and the last time I got a more verbose error:

```
Traceback (most recent call last):
  File "/usr/bin/protonvpn", line 11, in <module>
    load_entry_point('protonvpn-cli==2.2.4', 'console_scripts', 'protonvpn')()
  File "/usr/lib/python3.8/site-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/lib/python3.8/site-packages/protonvpn_cli/cli.py", line 139, in cli
    connection.status()
  File "/usr/lib/python3.8/site-packages/protonvpn_cli/connection.py", line 394, in status
    servers = get_servers()
  File "/usr/lib/python3.8/site-packages/protonvpn_cli/utils.py", line 102, in get_servers
    server_data = json.load(f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 377759 (char 377758)
Traceback (most recent call last):
  File "/usr/bin/protonvpn-applet", line 68, in run
    raise VPNStatusException('Cannot parse protonvpn-cli status output.')
__main__.VPNStatusException: Cannot parse protonvpn-cli status output.
```

**Comment by seadanda** [comment]
Hi @elshize, Unfortunately I can't replicate your problem as it seems the protonvpn servers are down. I am getting errors from the upstream protonvpn cli client that it can't connect to the API and when I tried to check the website it was also down. Can you confirm that you can see the same thing?
you can check by just running `protonvpn c -f` in a terminal and see what it returns. Basically this error from protonvpn-applet means "protonvpn backend is acting strangely and doesn't return the actual status"

**Comment by elshize** [comment]
I haven't experienced any problems that I noticed with protonvpn, it's connecting just fine right now as well. In any case, I think the right way of approaching this would be handling this error, sending a notification on error, saying "Cannot parse protonvpn-cli status output.", and if possible actually printing the status output to stderr for debugging. What do you think?

I'm trying it out again today, I'll try to catch it when it fails (if it fails) and see what the status output is in the terminal. Maybe that can answer some questions.

**Comment by seadanda** [comment]
I've actually found an [issue](https://github.com/ProtonVPN/linux-cli/issues/172) related to this in the upstream ProtonVPN repo. I must admit I haven't been using ProtonVPN for a couple of months because it doesn't play nicely with my DNS server (`unbound`) and I've been too busy in work to tinker.

What you're suggesting sounds like the right course to me, and I agree that it should not just die silently with no information about what the output was that couldn't be parsed. I'll switch to a different DNS server and bugfix, but might not have a lot of time today.

Thanks for the feedback, it's great to see people using it. Hopefully this will give me a push to merge all of the local improvements and other feature branches I've had sitting about for a few months.

**Comment by elshize** [comment]
Take your time. I'd love to help out at some point but also a bit busy for the next few days. I might look into writing some tests when I get a chance, seems like could be helpful.

**Comment by seadanda** [comment]
Nice one, that would be great. I'm keen to get back into this project now that I should have a bit more time over the summer and have a lot of features in mind that I'd like to add.
